CREATE TABLE "tracks" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "artists" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "labels" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "genres" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "styles" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "videos" ("id" integer primary key autoincrement,"name" varchar(255) );
CREATE TABLE "release_tracks" ("release_id" bigint,"track_id" bigint, PRIMARY KEY ("release_id","track_id"));
CREATE TABLE "release_artists" ("release_id" bigint,"artist_id" bigint, PRIMARY KEY ("release_id","artist_id"));
CREATE TABLE "release_labels" ("release_id" bigint,"label_id" bigint, PRIMARY KEY ("release_id","label_id"));
CREATE TABLE "release_genres" ("release_id" bigint,"genre_id" bigint, PRIMARY KEY ("release_id","genre_id"));
CREATE TABLE "release_styles" ("release_id" bigint,"style_id" bigint, PRIMARY KEY ("release_id","style_id"));
CREATE TABLE "release_videos" ("release_id" bigint,"video_id" bigint, PRIMARY KEY ("release_id","video_id"));
CREATE TABLE "releases" ("id" integer primary key autoincrement,"country" varchar(255),"notes" varchar(255),"title" varchar(255),"release_date" datetime,"created_at" datetime,"scraped" bool );
